# Generated by Django 5.0.6 on 2026-05-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('meters', 'Meters'), ('yards', 'Yards'), ('pieces', 'Pieces'), ('kg', 'Kilograms'), ('grams', 'Grams'), ('tola', 'Tola')], default='meters', max_length=20),
        ),
    ]
